/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedPwaDiagnosticsRouteImport } from './routes/_authenticated/pwa-diagnostics'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPensRouteImport } from './routes/_authenticated/pens'
import { Route as AuthenticatedLittersRouteImport } from './routes/_authenticated/litters'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedGardenRouteImport } from './routes/_authenticated/garden'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompostRouteImport } from './routes/_authenticated/compost'
import { Route as AuthenticatedChoresRouteImport } from './routes/_authenticated/chores'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBreedingRouteImport } from './routes/_authenticated/breeding'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedBarterRouteImport } from './routes/_authenticated/barter'
import { Route as AuthenticatedAppUpdatesRouteImport } from './routes/_authenticated/app-updates'
import { Route as AuthenticatedAnimalsIndexRouteImport } from './routes/_authenticated/animals.index'
import { Route as AuthenticatedAnimalsAnimalIdRouteImport } from './routes/_authenticated/animals.$animalId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminBackupsRouteImport } from './routes/_authenticated/admin.backups'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPwaDiagnosticsRoute =
  AuthenticatedPwaDiagnosticsRouteImport.update({
    id: '/pwa-diagnostics',
    path: '/pwa-diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPensRoute = AuthenticatedPensRouteImport.update({
  id: '/pens',
  path: '/pens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLittersRoute = AuthenticatedLittersRouteImport.update({
  id: '/litters',
  path: '/litters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGardenRoute = AuthenticatedGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompostRoute = AuthenticatedCompostRouteImport.update({
  id: '/compost',
  path: '/compost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChoresRoute = AuthenticatedChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBreedingRoute = AuthenticatedBreedingRouteImport.update({
  id: '/breeding',
  path: '/breeding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBarterRoute = AuthenticatedBarterRouteImport.update({
  id: '/barter',
  path: '/barter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppUpdatesRoute = AuthenticatedAppUpdatesRouteImport.update({
  id: '/app-updates',
  path: '/app-updates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnimalsIndexRoute =
  AuthenticatedAnimalsIndexRouteImport.update({
    id: '/animals/',
    path: '/animals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnimalsAnimalIdRoute =
  AuthenticatedAnimalsAnimalIdRouteImport.update({
    id: '/animals/$animalId',
    path: '/animals/$animalId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminBackupsRoute =
  AuthenticatedAdminBackupsRouteImport.update({
    id: '/admin/backups',
    path: '/admin/backups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app-updates': typeof AuthenticatedAppUpdatesRoute
  '/barter': typeof AuthenticatedBarterRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/breeding': typeof AuthenticatedBreedingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/chores': typeof AuthenticatedChoresRoute
  '/compost': typeof AuthenticatedCompostRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/litters': typeof AuthenticatedLittersRoute
  '/pens': typeof AuthenticatedPensRoute
  '/production': typeof AuthenticatedProductionRoute
  '/pwa-diagnostics': typeof AuthenticatedPwaDiagnosticsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/animals/$animalId': typeof AuthenticatedAnimalsAnimalIdRoute
  '/animals/': typeof AuthenticatedAnimalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app-updates': typeof AuthenticatedAppUpdatesRoute
  '/barter': typeof AuthenticatedBarterRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/breeding': typeof AuthenticatedBreedingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/chores': typeof AuthenticatedChoresRoute
  '/compost': typeof AuthenticatedCompostRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/litters': typeof AuthenticatedLittersRoute
  '/pens': typeof AuthenticatedPensRoute
  '/production': typeof AuthenticatedProductionRoute
  '/pwa-diagnostics': typeof AuthenticatedPwaDiagnosticsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/animals/$animalId': typeof AuthenticatedAnimalsAnimalIdRoute
  '/animals': typeof AuthenticatedAnimalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/app-updates': typeof AuthenticatedAppUpdatesRoute
  '/_authenticated/barter': typeof AuthenticatedBarterRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/breeding': typeof AuthenticatedBreedingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/chores': typeof AuthenticatedChoresRoute
  '/_authenticated/compost': typeof AuthenticatedCompostRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/garden': typeof AuthenticatedGardenRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/litters': typeof AuthenticatedLittersRoute
  '/_authenticated/pens': typeof AuthenticatedPensRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/pwa-diagnostics': typeof AuthenticatedPwaDiagnosticsRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/admin/backups': typeof AuthenticatedAdminBackupsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/animals/$animalId': typeof AuthenticatedAnimalsAnimalIdRoute
  '/_authenticated/animals/': typeof AuthenticatedAnimalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app-updates'
    | '/barter'
    | '/bills'
    | '/breeding'
    | '/calendar'
    | '/changelog'
    | '/chores'
    | '/compost'
    | '/contacts'
    | '/dashboard'
    | '/feed'
    | '/garden'
    | '/income'
    | '/litters'
    | '/pens'
    | '/production'
    | '/pwa-diagnostics'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/admin/backups'
    | '/admin/roles'
    | '/admin/users'
    | '/animals/$animalId'
    | '/animals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app-updates'
    | '/barter'
    | '/bills'
    | '/breeding'
    | '/calendar'
    | '/changelog'
    | '/chores'
    | '/compost'
    | '/contacts'
    | '/dashboard'
    | '/feed'
    | '/garden'
    | '/income'
    | '/litters'
    | '/pens'
    | '/production'
    | '/pwa-diagnostics'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/admin/backups'
    | '/admin/roles'
    | '/admin/users'
    | '/animals/$animalId'
    | '/animals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/app-updates'
    | '/_authenticated/barter'
    | '/_authenticated/bills'
    | '/_authenticated/breeding'
    | '/_authenticated/calendar'
    | '/_authenticated/changelog'
    | '/_authenticated/chores'
    | '/_authenticated/compost'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/garden'
    | '/_authenticated/income'
    | '/_authenticated/litters'
    | '/_authenticated/pens'
    | '/_authenticated/production'
    | '/_authenticated/pwa-diagnostics'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/admin/backups'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/animals/$animalId'
    | '/_authenticated/animals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pwa-diagnostics': {
      id: '/_authenticated/pwa-diagnostics'
      path: '/pwa-diagnostics'
      fullPath: '/pwa-diagnostics'
      preLoaderRoute: typeof AuthenticatedPwaDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pens': {
      id: '/_authenticated/pens'
      path: '/pens'
      fullPath: '/pens'
      preLoaderRoute: typeof AuthenticatedPensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/litters': {
      id: '/_authenticated/litters'
      path: '/litters'
      fullPath: '/litters'
      preLoaderRoute: typeof AuthenticatedLittersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garden': {
      id: '/_authenticated/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof AuthenticatedGardenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compost': {
      id: '/_authenticated/compost'
      path: '/compost'
      fullPath: '/compost'
      preLoaderRoute: typeof AuthenticatedCompostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chores': {
      id: '/_authenticated/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof AuthenticatedChoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/breeding': {
      id: '/_authenticated/breeding'
      path: '/breeding'
      fullPath: '/breeding'
      preLoaderRoute: typeof AuthenticatedBreedingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barter': {
      id: '/_authenticated/barter'
      path: '/barter'
      fullPath: '/barter'
      preLoaderRoute: typeof AuthenticatedBarterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-updates': {
      id: '/_authenticated/app-updates'
      path: '/app-updates'
      fullPath: '/app-updates'
      preLoaderRoute: typeof AuthenticatedAppUpdatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/animals/': {
      id: '/_authenticated/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AuthenticatedAnimalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/animals/$animalId': {
      id: '/_authenticated/animals/$animalId'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AuthenticatedAnimalsAnimalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/backups': {
      id: '/_authenticated/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AuthenticatedAdminBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppUpdatesRoute: typeof AuthenticatedAppUpdatesRoute
  AuthenticatedBarterRoute: typeof AuthenticatedBarterRoute
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedBreedingRoute: typeof AuthenticatedBreedingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedChoresRoute: typeof AuthenticatedChoresRoute
  AuthenticatedCompostRoute: typeof AuthenticatedCompostRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGardenRoute: typeof AuthenticatedGardenRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedLittersRoute: typeof AuthenticatedLittersRoute
  AuthenticatedPensRoute: typeof AuthenticatedPensRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedPwaDiagnosticsRoute: typeof AuthenticatedPwaDiagnosticsRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedAdminBackupsRoute: typeof AuthenticatedAdminBackupsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAnimalsAnimalIdRoute: typeof AuthenticatedAnimalsAnimalIdRoute
  AuthenticatedAnimalsIndexRoute: typeof AuthenticatedAnimalsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppUpdatesRoute: AuthenticatedAppUpdatesRoute,
  AuthenticatedBarterRoute: AuthenticatedBarterRoute,
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedBreedingRoute: AuthenticatedBreedingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedChoresRoute: AuthenticatedChoresRoute,
  AuthenticatedCompostRoute: AuthenticatedCompostRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGardenRoute: AuthenticatedGardenRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedLittersRoute: AuthenticatedLittersRoute,
  AuthenticatedPensRoute: AuthenticatedPensRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedPwaDiagnosticsRoute: AuthenticatedPwaDiagnosticsRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedAdminBackupsRoute: AuthenticatedAdminBackupsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAnimalsAnimalIdRoute: AuthenticatedAnimalsAnimalIdRoute,
  AuthenticatedAnimalsIndexRoute: AuthenticatedAnimalsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
